### Registro de usuario (secretaria)
# @name register_secretary
POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
  "email": "secretaria@mail.com",
  "password": "123456",
  "role": "secretary"
}

### Login como secretaria
# @name login_secretary
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
  "email": "secretaria@mail.com",
  "password": "123456"
}

### Token secretaria guardado en variable global
@token_secretary = {{login_secretary.response.body.token}}

### Endpoint protegido (secretaria)
GET http://localhost:3001/api/protected
Authorization: Bearer {{token_secretary}}

### Obtener actividades de secretarias
GET http://localhost:3001/api/secretary-activities
Authorization: Bearer {{token_secretary}}

### Crear paciente con persona de referencia
POST http://localhost:3001/api/patients/register
Content-Type: application/json
Authorization: Bearer {{token_secretary}}

{
  "first_name": "Ana",
  "last_name": "López",
  "date_of_birth": "1985-05-10",
  "address": "Calle Nueva 789",
  "phone": "555123456",
  "email": "ana.lopez@mail.com",
  "password": "123456",
  "preferred_payment_methods": "transferencia",
  "health_insurance_id": null,
  "reference_person": {
    "name": "Carlos",
    "last_name": "López",
    "address": "Calle Vieja 321",
    "phone": "555987654",
    "relationship": "Padre"
  }
}

### Consultar todos los pacientes (secretaria)
GET http://localhost:3001/api/patients
Authorization: Bearer {{token_secretary}}

### Consultar paciente por ID (secretaria)
GET http://localhost:3001/api/patients/100001
Authorization: Bearer {{token_secretary}}

### Actualizar persona de referencia de un paciente (secretaria)
PUT http://localhost:3001/api/patients/100001
Content-Type: application/json
Authorization: Bearer {{token_secretary}}

{
  "reference_person": {
    "name": "Miguel",
    "last_name": "López",
    "address": "Calle Nueva 456",
    "phone": "555222333",
    "relationship": "Hermano"
  }
}

### Agregar persona de referencia a un paciente
POST http://localhost:3001/api/patient-references/100001
Content-Type: application/json
Authorization: Bearer {{token_secretary}}

{
  "dni": "234526829",
  "name": "Carlos",
  "last_name": "López",
  "address": "Calle Nueva 456",
  "phone": "55522233",
  "relationship": "Padre"
}

### Listar personas de referencia de un paciente
GET http://localhost:3001/api/patient-references/100001
Authorization: Bearer {{token_secretary}}

### Actualizar persona de referencia
PUT http://localhost:3001/api/patient-references/100001/4
Content-Type: application/json
Authorization: Bearer {{token_secretary}}

{
  "dni": "23452829",
  "name": "Carlos",
  "last_name": "López",
  "address": "Calle Nueva 456",
  "phone": "555222334",
  "relationship": "Padre actualizado"
}

### Eliminar persona de referencia
DELETE http://localhost:3001/api/patient-references/100001/4
Authorization: Bearer {{token_secretary}}

### Ver medicamentos del historial medico
GET http://localhost:3001/api/medical-history/100001/prescribed-meds
Authorization: Bearer {{token_secretary}}




### Actualizar medicamento de historial médico
PUT http://localhost:3001/api/medical-history/100001/prescribed-meds/930001
Content-Type: application/json
Authorization: Bearer {{token_secretary}}

{
  "medication_name": "Losartán",
  "dose": "100mg",
  "instructions": "1 comprimido diario"
}

### Eliminar medicamento de historial médico
DELETE http://localhost:3001/api/medical-history/700001/prescribed-meds/930001
Authorization: Bearer {{token_secretary}} 